// This file is automatically generated. Do not modify it manually.
// To regenerate this file, run the `scaffold-firebase` command.

export const firebaseConfig = {
  "projectId": "studio-4979959136-15201",
  "appId": "1:53151350620:web:5d0df59458969818da0b99",
  "apiKey": "AIzaSyBbQAr88_6kAAQsRuWD_eQZkdPMMi3bsAE",
  "authDomain": "studio-4979959136-15201.firebaseapp.com",
  "storageBucket": "studio-4979959136-15201.appspot.com",
  "messagingSenderId": "53151350620",
};
